fetch_prs:
  description: "Fetch open PRs from the repository."
  expected_output: "A list of open PRs with metadata including title, description, and file changes."

review_prs:
  description: "Analyze each PR and leave comments with questions or suggestions."
  expected_output: "Comments on the PR discussing potential improvements or requesting clarifications."
