analyze_repository_context:
  description: |
    Build comprehensive project context:
    - Read and analyze repository README
    - Understand project structure and architecture
    - Review contribution guidelines
    - Identify key project patterns and standards
    - Map dependencies and integrations
  expected_output: Project context report with key architectural and standard guidelines

gather_pr_information:
  description: |
    Collect and analyze all PR information:
    - List all modified files
    - Get PR description and context
    - Identify key changes and their purpose
  expected_output: Comprehensive report of PR changes and context

technical_analysis:
  description: |
    Perform technical code quality assessment:
    - Code style and linting checks
    - Test coverage analysis
    - Identify potential technical debt
    - Check for security concerns
  expected_output: Technical analysis report with specific findings

requirements_validation:
  description: |
    Validate code changes against requirements:
    - Compare changes with PR description
    - Verify alignment with project standards
    - Check architectural consistency
    - Assess impact on existing functionality
  expected_output: Validation report with requirements compliance status

review_completion_check:
  description: |
    Evaluate review completeness:
    - Review all previous task outputs
    - Identify any gaps in the review
    - Determine if additional information is needed
  expected_output: Review status report with completion assessment

request_changes:
  description: |
    Handle necessary change requests:
    - Compile all identified issues
    - Format clear and actionable feedback
    - Prioritize requested changes
    - Provide helpful suggestions for improvements
  expected_output: Formatted change requests ready for PR comments

summary_task:
  description: "Compile feedback from all agents and post a summary comment on the PR."
  expected_output: "Compile feedback from all agents and post a summary comment on the PR. End execution of review"